spring.application.name=16-datajpa-oneToOne-app

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbms2_db
spring.datasource.username=root
spring.datasource.password=nitin@N33

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
