spring.application.name=09-datajpa-h2-app



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbms1_db
spring.datasource.username=root
spring.datasource.password=nitin@N33

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

